### ISSUE TITLE
[ Bug ]: Missing Line Break in Hash Example

### ISSUE THREAD

**Issue by mikoloism** [denoland/docs#1003]
![image](https://github.com/user-attachments/assets/99f9b414-7ac6-4d48-b9f1-7003fffeaad0)

NOTE: only in wide-screen this happen!

**Comment by matthewcarlino** [comment]
This occurs when the snippet has text but no code.  One easy solution is to remove the `md` styling and just stick with `sm` style, which looks reasonable even on wider screen imo.  But we loose the big giant code block at sizes > 768px (md)

![image](https://github.com/user-attachments/assets/a58675a6-5474-4ab7-83df-45ed3b66c484)

**Comment by shortOfCode** [comment]
Finally got back to this... Browsing around the other examples, those snippets with text but lacking code seem to serve well as context separators.  So I would suggest just adding some margin below.  I'll submit a PR with that change for review.
