### ISSUE TITLE
Vue tutorial

### ISSUE THREAD

**Issue by sc0paf** [denoland/docs#1046]
Someone posted an issue for this yesterday and was discussed in discord, but they closed the issue once they found a workaround, so I think the issue still exists. Pardon my ignorance if this is just an inexperience problem. 

https://docs.deno.com/runtime/tutorials/how_to_with_npm/vue/

Tutorial has user run
`deno run -A npm:create-vite`

Progress through vite scaffolding.  (Note 1 - For my inline VScode terminal on MacOS you're required to press some key and enter to get back to the command line, but that could be a thing specific to my setup so probably fine.)

Tutorial then says run: 
`cd [new-directory]`
`deno task dev`

Explicitly following these steps, myself (and other user) got `vite: command not found`

The appropriate tutorial steps seem to be from right after `deno run -A npm:create-vite`:
`cd [new directory]`
`deno install`
`cd ..`
`deno task dev`

**Comment by matthewcarlino** [comment]
@sc0paf  It appears that between `deno install` and `deno task dev`, one is not meant to `cd ..`.  That would certainly cause an error.  I've tried it without the `cd ..` and it worked well.

If the `cd..` was in the docs, it seems to have been removed.  So perhaps we are good here?

**Comment by sc0paf** [comment]
It was missing the `deno install` when I posted this - but someone seems to have updated it now. This is indeed solved.
