### ISSUE TITLE
React App tutorial leaving out proxy configuration for Development server

### ISSUE THREAD

**Issue by casperlehmann** [denoland/docs#1048]
The [Build React App](https://docs.deno.com/runtime/tutorials/how_to_with_npm/react/) page has a few issues. Oddly, it does not seem to be up-to-date with the implementation in the [latest master of denoland/tutorial-with-react](https://github.com/denoland/tutorial-with-react/tree/74206e0eb649d7a4ea6b82cb6d4a00bb77171c57) (which works, and to which it contains a direct link).

When creating the project using `deno run -A npm:create-vite@latest demo --template react-ts`, the application will automatically be configured to use the `Vite` development server. We then change the `dev` configuration, but the main app is still being served using Vite server.

See `package.json`:

``` diff
    "scripts": {
-     "dev": "vite",
+     "dev": "deno task dev:api & deno task dev:vite",
+     "dev:api": "deno run --allow-env --allow-net api/main.ts",
+     "dev:vite": "deno run -A npm:vite",
```

Vite uses port `5173` (spelling Vite in 1337 speak) out of the box while the API is being hosted on port `8000`. Therefore, the Vite server needs to be configured with a proxy for accessing the `api/` paths on port `8000`, while the main application will remain on port `5173`.

**Comment by thisisjofrank** [comment]
Fixed in https://github.com/denoland/docs/pull/1050
