### ISSUE TITLE
React App tutorial leaving out CSS class styling

### ISSUE THREAD

**Issue by casperlehmann** [denoland/docs#1049]
The [Build React App](https://docs.deno.com/runtime/tutorials/how_to_with_npm/react/) page has a few issues. Oddly, it does not seem to be up-to-date with the implementation in the [latest master of denoland/tutorial-with-react](https://github.com/denoland/tutorial-with-react/tree/74206e0eb649d7a4ea6b82cb6d4a00bb77171c57) (which works, and to which it contains a direct link).

This issue in particular is related to missing css configuration for the `.dinosaur` class which results in the following layout:

<img width="1792" alt="Screenshot 2024-10-20 at 22 06 49" src="https://github.com/user-attachments/assets/7991a186-e2a2-47ce-867a-b0d6c92e9338">

We'll need to add the following to `src/App.css`:

``` css
.dinosaur {
  display: block;
}
```

**Comment by thisisjofrank** [comment]
This was fixed in https://github.com/denoland/docs/pull/1050
