### ISSUE TITLE
Add a feedback mechanism to the Docs pages

### ISSUE THREAD

**Issue by thisisjofrank** [denoland/docs#1083]
Users should be able to feedback on whether the page was valuable, and should be able to easily make PRs on particular pages with a 'edit this on github' type link, which goes straight to the particular page.

Much like what Github have on their documentation

![image](https://github.com/user-attachments/assets/107a8039-e57e-4fd7-ba06-5a1810ba3c9f)

**Comment by thisisjofrank** [comment]
Feedback is now live on the site

**Comment by dandv** [comment]
> should be able to easily make PRs on particular pages with a 'edit this on github' type link

Was this implemented by #342, or a different implementation? Asking because I'm [running into links that point to the wrong files](https://github.com/denoland/docs/issues/342#issuecomment-2543649073).
