### ISSUE TITLE
Add Play Button for Running Code in Deno Docs

### ISSUE THREAD

**Issue by akshit-vadodariya-st9** [denoland/docs#1085]
### Description
To enhance the user experience and interactivity of our Deno documentation, we propose adding a "Play" button next to code snippets. This button will allow users to run the code directly in an embedded Deno playground, providing immediate feedback and a hands-on learning experience.

Example: 
![playgraund](https://github.com/user-attachments/assets/06655eda-2fb6-4048-8138-da95028cd384)

**Comment by thisisjofrank** [comment]
This is not a priority right now.
