### ISSUE TITLE
Incorrect settings example

### ISSUE THREAD

**Issue by nhrones** [denoland/docs#1099]
The page: 
https://docs.deno.com/runtime/getting_started/setup_your_environment/
shows an incorect ./.vscode.json example after running -- Deno: Initialize Workspace Configuration
The example shows three settings, while the new command only writes one.
This created some confusion for a new Deno user.

**Comment by nhrones** [comment]
@thisisjofrank  If you click the doc link above, you'll see that it still shows the three settings.  This is very confusing for new users.  When will that page be corrected?

**Comment by thisisjofrank** [comment]
The fix has now been merged. Can you now see the update? @nhrones

**Comment by nhrones** [comment]
Yes.  Thanks for this.
