### ISSUE TITLE
Docs include not allowed target property

### ISSUE THREAD

**Issue by stefnotch** [denoland/docs#1109]
The documentation at
https://github.com/denoland/docs/blob/main/runtime/reference/ts_config_migration.md#targeting-deno-and-the-browser

says
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "dom.asynciterable", "deno.ns"]
  }
}
```

However, upon typing that into my `deno.json`, I get
> Property target is not allowed.

![image](https://github.com/user-attachments/assets/58b7836b-4f96-4c85-b01e-09c2c4f18534)

Does this documentation need to be updated, or is the tooling wrong?

**Comment by thisisjofrank** [comment]
You're indeed correct, ESNext is hardcoded and therefore not allowed to be set. Thanks for spotting this! I'll remove it from the docs.

**Comment by thisisjofrank** [comment]
This has now been merged, thanks for the catch!

**Comment by stefnotch** [comment]
Sweet! Always glad to see Deno being simple and choosing sensible defaults.
