### ISSUE TITLE
Add Internationalization (i18n)

### ISSUE THREAD

**Issue by Gugustinette** [denoland/docs#1250]
Having Deno's website and documentation in other languages than english would be nice 😄

Lume seems to have support for [multiple languages](https://lume.land/plugins/multilanguage), so I guess it isn't too much of a pain to configure ?

I can work on the french version 👍

**Comment by kt3k** [comment]
I'm not sure about the current policy, but we used to have translations of docs and deprecated them at some point because we couldn't keep them up to date. https://github.com/denoland/dotland/pull/2150

**Comment by marvinhagemeister** [comment]
yeah we decided against it, because we don't have the resources to keep multiple translations up to date.

**Comment by Gugustinette** [comment]
That's understandable !

Great thing anyway to have an issue stating it, this issue can be closed for now !
