### ISSUE TITLE
Web framework in the same level as basic

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/docs#211]
The web framework section in https://docs.deno.com/runtime/manual/getting_started/web_frameworks should be rename : << web framework and js tools >> and create new section for it in the the same level as Basic, Using & Publishing deno modules,...in addition of speaking about deno native framework, node native framework, we talk about js tools, like vite....
This section a guide for new deno users coming from node and other env.

**Comment by thisisjofrank** [comment]
Page has now been moved
