### ISSUE TITLE
feature request: edit this page

### ISSUE THREAD

**Issue by scarf005** [denoland/docs#342]
e.g for this page: https://docs.deno.com/runtime/manual/basics/testing/

having an `edit this page` button that [links to the same file](https://github.com/denoland/deno-docs/blob/main/runtime/manual/basics/testing/index.md) will make it easier to edit documents.

**Comment by thisisjofrank** [comment]
This is now live. Each docs page has a feedback and a direct link to edit on github. Added in https://github.com/denoland/docs/pull/1097

**Comment by scarf005** [comment]
thanks! forgot this issue existed.

**Comment by dandv** [comment]
I've run into some "Edit this page" links that point to completely different files vs. the source of the current page. Just some examples:
* https://docs.deno.com/runtime/reference/cli/test/ points to the much shorter https://github.com/denoland/docs/edit/main/runtime/reference/cli/test.md
* #1265
