### ISSUE TITLE
Ensure all deno CLI commands have corresponding doc pages

### ISSUE THREAD

**Issue by kwhinnery** [denoland/docs#356]
We should audit the current full list of deno CLI commands and ensure docs are present and up to date.
- Run `deno help` 
- Audit list of commands and ensure doc pages exist
- Ensure the command name appears in the h1 for the doc pages
- Audit search results - e.g. when you search "deno compile", it should link to [this page](https://docs.deno.com/runtime/manual/tools/compiler)
- Update/sync up doc pages with actual options and behavior of the commands - these can get out of date

**Comment by thisisjofrank** [comment]
These are now auto generated
