### ISSUE TITLE
"Deploy System Status" link in the footer is non-functional

### ISSUE THREAD

**Issue by hampuskraft** [denoland/docs#435]
https://github.com/denoland/deno-docs/blob/7e14ace5bb49906387fee831e91ba94d686bf8e0/docusaurus.config.js#L215

I noticed that this link leads to `https://www.denostatus.com` ([isup.me](<https://isup.me/denostatus.com?proto=https&www=1>)) instead of `https://denostatus.com`. It seems that the `www` subdomain currently never resolves, which indicates a problem with your configuration.

**Comment by thisisjofrank** [comment]
This is now fixed
