### ISSUE TITLE
Shorten example command URLs

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/docs#473]
On https://docs.deno.com/examples/http-server-websocket the command to run the example is quite long:

```sh
deno run --allow-net https://raw.githubusercontent.com/denoland/deno-docs/main/by-example/http-server-websocket.ts
```

**Comment by marvinhagemeister** [comment]
We should probably host all kinds of example modules directly on JSR, that way it would just be:

```sh
deno serve jsr:@deno-docs/http-server-websocket
```

**Comment by dsherret** [comment]
I'm not sure about storing the examples on JSR. JSR somewhat obscures the source by making it internal to the package whereas with an https url you can copy and paste it into your browser to see the source. Also, it's nice to keep the code close to the documentation.

**Comment by thisisjofrank** [comment]
Should we just host it in a /static folder on docs?

**Comment by marvinhagemeister** [comment]
Fair point, makes more sense to have them in the same repo instead of somewhere external on JSR.

**Comment by thisisjofrank** [comment]
This is now done
