### ISSUE TITLE
Embed API reference docs in docs.deno.com/api/

### ISSUE THREAD

**Issue by donjo** [denoland/docs#488]
Issue to capture the work necessary to embed the content that is rendered via https://api-reference.deno.dev/api/deno/ into the API reference section of docs.deno.com/api

{ Placeholder to update with a task list once technical approach is established }

Example:
![Image](https://github.com/denoland/deno-docs/assets/776987/2b939564-49d6-4e31-9ec0-c12ee4f38273)

**Comment by rbetts** [comment]
Need to decide: how to host this beside docusaurus. Server the `/api` route separately and reproduce the header.  To start - consider brute-force replicating the header.
