### ISSUE TITLE
API category left nav not extending all the way down the page

### ISSUE THREAD

**Issue by donjo** [denoland/docs#546]
<img width="1477" alt="Screenshot 2024-07-05 at 3 14 28 PM" src="https://github.com/denoland/deno-docs/assets/776987/bb2abff3-0998-47fa-b731-3f1b1314f4fd">

Categories should extend to the bottom of the page so the border line doesn't go away when you scroll past the initial viewport.

Additionally the left nav should show all items in the list if the content body is longer than the nav, right now it cuts off additional items and there is no indication that you can scroll that area.

In the example above there are a number of items beyond "punycode"

**Comment by crowlKats** [comment]
This is fixed
