### ISSUE TITLE
`deno check` docs are just a copy of `deno cache`?

### ISSUE THREAD

**Issue by lucacasonato** [denoland/docs#631]
https://docs.deno.com/runtime/manual/tools/check/ right now is pretty much identical to `deno check`?

**Comment by thisisjofrank** [comment]
I don't think im seeing what you're seeing. These two?
https://docs.deno.com/runtime/manual/tools/check/
https://docs.deno.com/runtime/manual/tools/cache/

**Comment by lucacasonato** [comment]
I started fixing it in https://github.com/denoland/deno-docs/commit/3114421eac584a21ab974e10728b0b131b498e5e (see how it was prior). But the option section is still identical. We should also link to the "TypeScript in Deno" section from the subcommand docs.

Main thing that is missing docs is `--all` flag

**Comment by thisisjofrank** [comment]
Now fixed
