### ISSUE TITLE
Supported Node APIs and globals

### ISSUE THREAD

**Issue by thisisjofrank** [denoland/docs#672]
https://docs.deno.com/runtime/manual/node/compatibility/

This needs restyling

**Comment by donjo** [comment]
Any thoughts on how this should be represented? At the very least I think the <details> element needs some restyling so it isn't pink not quite as big but this content may be better served if it were all auto-expanded with each one being a header maybe? 

And now that we have API reference stuff built in do we want to change out all those links to something on our own domain?

**Comment by thisisjofrank** [comment]
Yeah, the pink definitely needs changing. Perhaps a table rather than the accordions? Yeah, I was wondering about the links. Seems sensible to me.

**Comment by thisisjofrank** [comment]
Something along these lines, 

![Image](https://github.com/user-attachments/assets/ef1a3a1e-3aa5-4494-80ab-e373f97b153e)

Where the name itself is the link to the docs, and there is a clear indication of full support or stubbed support (which require no further text) and then an expandy box for the ones that are partial support

**Comment by donjo** [comment]
fixed in #843
