### ISSUE TITLE
jsx precompile option isn't mentioned in docs

### ISSUE THREAD

**Issue by ry** [denoland/docs#701]
https://deno.com/blog/v1.38#fastest-jsx-transform

also note the warning in hono's docs https://hono.dev/docs/middleware/builtin/jsx-renderer#userequestcontext

**Comment by dmint789** [comment]
I also just stumbled upon this. The docs should mention what this means, since this is not one of the options in `tsconfig.json` [docs](https://www.typescriptlang.org/tsconfig/jsx.html).
