### ISSUE TITLE
Add running JS/TS tests in `deno` repo to contribution guide

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/docs#718]
From discord https://discord.com/channels/684898665143206084/684911491035430919/1274850560692060213 

> how do I run deno tests inside deno repo ?, for example under tests/unit/os_test.ts
seems like I have to do 
target/debug/deno test -A --unstable --lock=tools/deno.lock.json --config tests/config/deno.json tests/unit
>
>
> but this is not documented in https://docs.deno.com/runtime/manual/references/contributing/

**Comment by irbull** [comment]
Should we close this, anymore you think we need here @marvinhagemeister
