### ISSUE TITLE
Docs Dark Mode

### ISSUE THREAD

**Issue by yet-another-tim** [denoland/docs#817]
Please consider adding a dark mode option to the docs.

Normally I would just use the web extension Dark Reader. However when I use it on your docs the code boxes are unreadable (background becomes white with text mostly illegible).

Thanks for all you do.

**Comment by jonkoops** [comment]
I would love this, for late night coding sessions a dark mode for the documentation would be amazing! Seems like this is also the [most upvoted issue](https://github.com/denoland/docs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by davis9001** [comment]
No promises yet but I started the process of getting this done.

**Comment by davis9001** [comment]
> No promises yet but I started the process of getting this done.

Alright I should have a pull request for this in the next couple of days or so.

**Comment by jonkoops** [comment]
Thanks for adding this, now my eyes can be at peace.
