### ISSUE TITLE
Broken link in the "Using modules in Deno" page

### ISSUE THREAD

**Issue by ec-fujiwara** [denoland/docs#838]
The section "Managing third party modules and libraries" in the article "Using modules in Deno" (https://docs.deno.com/runtime/fundamentals/modules/#managing-third-party-modules-and-libraries) has broken link.

Code:
https://github.com/denoland/docs/blob/main/runtime/fundamentals/modules.md?plain=1#L112

`/runtime/manual/basics/import_maps/` no longer exists.

**Comment by thisisjofrank** [comment]
https://github.com/denoland/docs/pull/851 Fixed here https://github.com/denoland/docs/pull/851
