### ISSUE TITLE
I couldn't do reference_gen

### ISSUE THREAD

**Issue by yabuki** [denoland/docs#840]
Hi document maintainer.

I couldn't generate reference. 
I did make reference last week, It was fine.

Is `reference_gen/deno.json` something wrong? It contains "manual" string.

Do this issue have relation of #838 issue?

```
$ deno task reference
Task reference cd reference_gen && deno task types && deno task doc
error: Failed deserializing config file 'file:///home/yabuki/scm/git/denoland/deno-docs-orig/reference_gen/deno.json'.

Caused by:
    invalid type: string "manual", expected a boolean
```

**Comment by yabuki** [comment]
git bisect says:

1cfb5e40dc2c1972cc0163b31a533ec52317f67e commit is something wrong. 
```
git bisect good b915c2c
1cfb5e40dc2c1972cc0163b31a533ec52317f67e is the first bad commit
commit 1cfb5e40dc2c1972cc0163b31a533ec52317f67e
```

**Comment by bartlomieju** [comment]
You need to update to RC release of Deno:
```
deno upgrade
deno upgrade rc
```

**Comment by yabuki** [comment]
Thanks! 
It works!
