### ISSUE TITLE
Depricate all refrences to skypack.dev

### ISSUE THREAD

**Issue by jcc10** [denoland/docs#88]
The skypack-cdn seems to be abandoned. No issue updates have been made recently and the search API on the website is broken. We should:

1. Preemptively replace links from `skypack.dev` to `esm.sh` to ensure if skypack.dev goes completely down new users won't be confused
2. Note on the node-faq page that the project seems to be abandoned and should not be used.

**Comment by thisisjofrank** [comment]
all references to skypack have now been removed
