### ISSUE TITLE
Missing documentation for `deno check` tool

### ISSUE THREAD

**Issue by glebbash** [denoland/docs#91]
I think it would be helpful to document `deno check` usage. I knew the command existed but it's usage is not that clear (including --help output).

I expected `deno check` to typecheck the whole project but it needs the file. Calling it like this `deno check **/**.ts` is also not what I was looking for. After some trial and error I figured out that it type-checks all of the imported files recursively so I basically needed to call `deno check src/mod.ts`.

Would be nice to clarify this in docs.

**Comment by thisisjofrank** [comment]
This now is documented here: https://docs.deno.com/runtime/reference/cli/check/
