### ISSUE TITLE
Code from section "Reading a file" warns "deprecation"

### ISSUE THREAD

**Issue by silvioprog** [denoland/docs#96]
The example uses `import { copy } from "https://deno.land/std@0.167.0/streams/conversion.ts";`, reporting the following warning:

```
@deprecated
(will be removed after 0.169.0) Import from std/streams/copy.ts instead.
```

It would be nice to upgrade it to use something like `import { copy } from "https://deno.land/std@0.167.0/streams/copy.ts";`.

**Comment by kwhinnery** [comment]
This is removed, but still appears in the docs - need to cull

**Comment by hashrock** [comment]
is this still appears in somewhere? I would be happy to help if you let me know the location.
