### ISSUE TITLE
Documentation calls `deno add` an alias for `deno install`, and `deno remove` alias for `deno uninstall`

### ISSUE THREAD

**Issue by matthewjnield** [denoland/docs#975]
The documentation page for the CLI runtime subcommand `deno install` (https://docs.deno.com/runtime/reference/cli/install/) says that the subcommand `deno add` is an alias for `deno install`.

I think that calling this an alias is misleading since the two commands do not do the same thing. `deno add` only updates the configuration file to add the specified dependency to the "imports" field. `deno install` actually downloads and installs dependencies on the user's computer.

![image](https://github.com/user-attachments/assets/51c80f8a-051a-4405-8e1c-69b2f25e3633)

Similarly, the documentation page for the CLI runtime subcommand `deno uninstall` (https://docs.deno.com/runtime/reference/cli/uninstall/) says that the subcommand `deno remove` is an alias for `deno uninstall`.

I think that calling this an alias is misleading since the two commands do not do the same thing. `deno remove` only updates the configuration file to remove the specified dependency from the "imports" field. `deno install` actually removes/uninstalls dependencies form the user's computer.

![image](https://github.com/user-attachments/assets/bcc4a4b9-e09a-474d-a51f-b6016e7f0719)

**Comment by thisisjofrank** [comment]
The tip is now deleted

**Comment by matthewjnield** [comment]
@thisisjofrank Thank you for looking at this issue. The tips appear to still be in the files for both pages (screenshots and line numbers shown below). If you agree with the suggestion to remove or modify these to be less misleading about what the subcommands do, I will gladly open a pull request with suggested changes.

`runtime/reference/cli/install.md`, lines 31 to 35

![image](https://github.com/user-attachments/assets/879aa9f4-82be-4b37-997d-41dd394828bc)


`runtime/reference/cli/uninstall.md`, lines 33 to 37

![image](https://github.com/user-attachments/assets/4cf24745-5f77-42f6-b86b-887349c930d4)
