### ISSUE TITLE
Missing spaces in Deno API docs

### ISSUE THREAD

**Issue by muzimuzhi** [denoland/docs#988]
https://docs.deno.com/api/deno/subprocess
![image](https://github.com/user-attachments/assets/bd22ba1c-ab52-4cf3-80a3-16f54f6b7fc0)

It seems the positions where spaces were missing are all newlines in the JSDoc sources. I didn't find the doc source of the second case, deprecated `Deno.process`.

https://github.com/denoland/deno/blob/94b588ce6624ae2f2ed648c7b1a479a10513542f/cli/tsc/dts/lib.deno.ns.d.ts#L3715-L3720
```ts
  /**
   * The interface for handling a child process returned from
   * {@linkcode Deno.Command.spawn}.
   *
   * @category Subprocess
   */
```

https://github.com/denoland/deno/blob/94b588ce6624ae2f2ed648c7b1a479a10513542f/cli/tsc/dts/lib.deno.ns.d.ts#L4595-L4598
```ts
  /** Send a signal to process under given `pid`. The value and meaning of the
   * `signal` to the process is operating system and process dependant.
   * {@linkcode Signal} provides the most common signals. Default signal
   * is `"SIGTERM"`.
   * ...
   */
```

**Comment by muzimuzhi** [comment]
The problem doesn't reproduce in the HTML doc generated from a simple `main.ts`, by running `deno doc --html main.ts`. Thus maybe it comes from codes in [./reference_gen](https://github.com/denoland/docs/tree/main/reference_gen).

```ts
/** Send a signal to process under given `pid`. The value and meaning of the
 * `signal` to the process is operating system and process dependant.
 * {@linkcode Signal} provides the most common signals. Default signal
 * is `"SIGTERM"`.
 */
export function add(a: number, b: number): number {
  return a + b;
}

if (import.meta.main) {
  console.log("Add 2 + 3 =", add(2, 3));
}
```

**Comment by crowlKats** [comment]
closing as fixed
